name: Python CI

on:
  push:
    # This empty 'branches:' or simply omitting it means it will run on all pushes to all branches
  pull_request:
    branches:
      - main # You might still want to limit PRs to 'main' or adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt

